adjust ci

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -134,30 +134,30 @@ jobs:
         uses: wangzuo/action-release-checksums@v1
         with:
           token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
-            # homebrew:
-            #   needs: release
-            #   runs-on: ubuntu-latest
-            #   strategy:
-            #     fail-fast: true
-            #   steps:
-            #     # https://github.com/Justintime50/homebrew-releaser
-            #     - name: homebrew releaser
-            #       uses: Justintime50/homebrew-releaser@v1
-            #       with:
-            #         debug: false
-            #         homebrew_owner: dotenvx
-            #         homebrew_tap: homebrew-brew
-            #         formula_folder: Formula
-            #         github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
-            #         commit_owner: motdotenv
-            #         commit_email: mot@dotenv.org
-            #         install: 'bin.install "dotenvx-ext-hub";'
-            #         test: 'system bin/"dotenvx-ext-hub", "--version";'
-            #         target_darwin_amd64: true
-            #         target_darwin_arm64: true
-            #         target_linux_amd64: true
-            #         target_linux_arm64: true
-            #         update_readme_table: true
+  # homebrew:
+  #   needs: release
+  #   runs-on: ubuntu-latest
+  #   strategy:
+  #     fail-fast: true
+  #   steps:
+  #     # https://github.com/Justintime50/homebrew-releaser
+  #     - name: homebrew releaser
+  #       uses: Justintime50/homebrew-releaser@v1
+  #       with:
+  #         debug: false
+  #         homebrew_owner: dotenvx
+  #         homebrew_tap: homebrew-brew
+  #         formula_folder: Formula
+  #         github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
+  #         commit_owner: motdotenv
+  #         commit_email: mot@dotenv.org
+  #         install: 'bin.install "dotenvx-ext-hub";'
+  #         test: 'system bin/"dotenvx-ext-hub", "--version";'
+  #         target_darwin_amd64: true
+  #         target_darwin_arm64: true
+  #         target_linux_amd64: true
+  #         target_linux_arm64: true
+  #         update_readme_table: true
   npm:
     needs: release
     runs-on: ubuntu-latest
@@ -323,8 +323,8 @@ jobs:
   publish-all:
     runs-on: ubuntu-latest
     needs: 
-      - homebrew
       - npm
+      # - homebrew
       - dotenvx-ext-hub-darwin-amd64
       - dotenvx-ext-hub-darwin-arm64
       - dotenvx-ext-hub-darwin-x86_64
@@ -338,65 +338,65 @@ jobs:
       - name: publish-all aggregate step
         run: echo "publish-all completed"
 
-          # dotenvx-sh:
-          #   needs: publish-all
-          #   runs-on: ubuntu-latest
-          #   strategy:
-          #     fail-fast: true
-          #   steps:
-          #     - uses: actions/checkout@v4
-          #     - name: extract version
-          #       run: |
-          #         VERSION=${GITHUB_REF#refs/tags/}
-          #         CLEAN_VERSION=${VERSION#v}
-          #         echo "VERSION=$VERSION" >> $GITHUB_ENV
-          #         echo "CLEAN_VERSION=$CLEAN_VERSION" >> $GITHUB_ENV
-          #     - name: update install.sh with VERSION
-          #       run: |
-          #         mkdir -p dist
-          #         sed "0,/^VERSION=\".*\"/s//VERSION=\"${{ env.CLEAN_VERSION }}\"/" install.sh > ./dist/install.sh
-          #     - name: checkout dotenvx/dotenvx.sh repo
-          #       uses: actions/checkout@v4
-          #       with:
-          #         repository: "dotenvx/dotenvx.sh"
-          #         token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
-          #         path: "dotenvx.sh"
-          #     - name: copy install.sh to dotenvx.sh repo
-          #       run: |
-          #         cp dist/install.sh dotenvx.sh/install.sh
-          #         echo "${{ env.CLEAN_VERSION }}" > dotenvx.sh/VERSION
-          #     - name: commit and push
-          #       run: |
-          #         cd dotenvx.sh
-          #         git config --global user.name 'motdotenv'
-          #         git config --global user.email 'mot@dotenv.org'
-          #         git add .
-          #         git commit -m "${{ env.VERSION }}" --allow-empty
-          #         git tag "${{ env.VERSION }}" --force
-          #         git push origin HEAD --tags --force
-          # confirm-dotenvx-sh:
-          #   needs: dotenvx-sh
-          #   runs-on: ubuntu-latest
-          #   strategy:
-          #     fail-fast: true
-          #   steps:
-          #     - name: extract version
-          #       run: |
-          #         VERSION=${GITHUB_REF#refs/tags/}
-          #         CLEAN_VERSION=${VERSION#v}
-          #         echo "VERSION=$VERSION" >> $GITHUB_ENV
-          #         echo "CLEAN_VERSION=$CLEAN_VERSION" >> $GITHUB_ENV
-          #     - name: wait for deployment
-          #       run: |
-          #         end=$((SECONDS+300))
-          #         while [ $SECONDS -lt $end ]; do
-          #           current_version=$(curl -s -L https://dotenvx.sh/VERSION)
-          #           if [ "$current_version" == "${{ env.CLEAN_VERSION }}" ]; then
-          #             echo "dotenvx.sh deployment successful with version $current_version"
-          #             exit 0
-          #           fi
-          #           echo "waiting for deployment..."
-          #           sleep 10
-          #         done
-          #         echo "[DEPLOYMENT_FAILED]: VERSION did not update to ${{ env.CLEAN_VERSION }} within 5 minutes"
-          #         exit 1
+  # dotenvx-sh:
+  #   needs: publish-all
+  #   runs-on: ubuntu-latest
+  #   strategy:
+  #     fail-fast: true
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - name: extract version
+  #       run: |
+  #         VERSION=${GITHUB_REF#refs/tags/}
+  #         CLEAN_VERSION=${VERSION#v}
+  #         echo "VERSION=$VERSION" >> $GITHUB_ENV
+  #         echo "CLEAN_VERSION=$CLEAN_VERSION" >> $GITHUB_ENV
+  #     - name: update install.sh with VERSION
+  #       run: |
+  #         mkdir -p dist
+  #         sed "0,/^VERSION=\".*\"/s//VERSION=\"${{ env.CLEAN_VERSION }}\"/" install.sh > ./dist/install.sh
+  #     - name: checkout dotenvx/dotenvx.sh repo
+  #       uses: actions/checkout@v4
+  #       with:
+  #         repository: "dotenvx/dotenvx.sh"
+  #         token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
+  #         path: "dotenvx.sh"
+  #     - name: copy install.sh to dotenvx.sh repo
+  #       run: |
+  #         cp dist/install.sh dotenvx.sh/install.sh
+  #         echo "${{ env.CLEAN_VERSION }}" > dotenvx.sh/VERSION
+  #     - name: commit and push
+  #       run: |
+  #         cd dotenvx.sh
+  #         git config --global user.name 'motdotenv'
+  #         git config --global user.email 'mot@dotenv.org'
+  #         git add .
+  #         git commit -m "${{ env.VERSION }}" --allow-empty
+  #         git tag "${{ env.VERSION }}" --force
+  #         git push origin HEAD --tags --force
+  # confirm-dotenvx-sh:
+  #   needs: dotenvx-sh
+  #   runs-on: ubuntu-latest
+  #   strategy:
+  #     fail-fast: true
+  #   steps:
+  #     - name: extract version
+  #       run: |
+  #         VERSION=${GITHUB_REF#refs/tags/}
+  #         CLEAN_VERSION=${VERSION#v}
+  #         echo "VERSION=$VERSION" >> $GITHUB_ENV
+  #         echo "CLEAN_VERSION=$CLEAN_VERSION" >> $GITHUB_ENV
+  #     - name: wait for deployment
+  #       run: |
+  #         end=$((SECONDS+300))
+  #         while [ $SECONDS -lt $end ]; do
+  #           current_version=$(curl -s -L https://dotenvx.sh/VERSION)
+  #           if [ "$current_version" == "${{ env.CLEAN_VERSION }}" ]; then
+  #             echo "dotenvx.sh deployment successful with version $current_version"
+  #             exit 0
+  #           fi
+  #           echo "waiting for deployment..."
+  #           sleep 10
+  #         done
+  #         echo "[DEPLOYMENT_FAILED]: VERSION did not update to ${{ env.CLEAN_VERSION }} within 5 minutes"
+  #         exit 1
